[package]
name = "torrentai"
version = "0.1.0"
edition = "2021"

[dependencies]
librqbit = "8.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
